//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobManagement.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнително описание.
        /// </summary>
        public static string AdditionalDescription {
            get {
                return ResourceManager.GetString("AdditionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бакалавърска степен.
        /// </summary>
        public static string Bachelor_s_degree {
            get {
                return ResourceManager.GetString("Bachelor\'s degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рожденна дата.
        /// </summary>
        public static string BdayDate {
            get {
                return ResourceManager.GetString("BdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to България.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бургас.
        /// </summary>
        public static string Burgas {
            get {
                return ResourceManager.GetString("Burgas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бизнес профил.
        /// </summary>
        public static string businessProfile {
            get {
                return ResourceManager.GetString("businessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бизнес сектор.
        /// </summary>
        public static string BusinessSector {
            get {
                return ResourceManager.GetString("BusinessSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa..
        /// </summary>
        public static string BusinessUserProfileDescriptionMsg {
            get {
                return ResourceManager.GetString("BusinessUserProfileDescriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бизнес сектор.
        /// </summary>
        public static string BusnessSector {
            get {
                return ResourceManager.GetString("BusnessSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери.
        /// </summary>
        public static string Choise {
            get {
                return ResourceManager.GetString("Choise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to избери файл.
        /// </summary>
        public static string ChoiseFile {
            get {
                return ResourceManager.GetString("ChoiseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави снимки в галерията.
        /// </summary>
        public static string ChoiseImage {
            get {
                return ResourceManager.GetString("ChoiseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете паролата.
        /// </summary>
        public static string ConformPassword {
            get {
                return ResourceManager.GetString("ConformPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не забравяйте своята парола.
        /// </summary>
        public static string DontForgotPass {
            get {
                return ResourceManager.GetString("DontForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля изберете образование.
        /// </summary>
        public static string EnterEducation {
            get {
                return ResourceManager.GetString("EnterEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете имейл адреса си.
        /// </summary>
        public static string EnterEmailAddress {
            get {
                return ResourceManager.GetString("EnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете парола.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жена.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да се провери.
        /// </summary>
        public static string ForgotPasswordEmailMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да се провери.
        /// </summary>
        public static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерия.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на снимки в моята галерия.
        /// </summary>
        public static string GalleryImages {
            get {
                return ResourceManager.GetString("GalleryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимки в моята галерия.
        /// </summary>
        public static string GalleryImagesBox {
            get {
                return ResourceManager.GetString("GalleryImagesBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимки галерия.
        /// </summary>
        public static string GalleryPictures {
            get {
                return ResourceManager.GetString("GalleryPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гимназиално образование.
        /// </summary>
        public static string GimnazeEducation {
            get {
                return ResourceManager.GetString("GimnazeEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате акаунт? Влезте:.
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравен статус.
        /// </summary>
        public static string HealthStatus {
            get {
                return ResourceManager.GetString("HealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съгласен съм с.
        /// </summary>
        public static string Idegree {
            get {
                return ResourceManager.GetString("Idegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, проверете имейла си за получени указания как да промените паролата си..
        /// </summary>
        public static string InstructionRessetPass {
            get {
                return ResourceManager.GetString("InstructionRessetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спомних си паролата!.
        /// </summary>
        public static string Irememberedmypass {
            get {
                return ResourceManager.GetString("Irememberedmypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид работа.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мъж.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mагистърска степен.
        /// </summary>
        public static string MastersDegree {
            get {
                return ResourceManager.GetString("MastersDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпочитам да не отговарям.
        /// </summary>
        public static string NoResponce {
            get {
                return ResourceManager.GetString("NoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямате акаунт? Регистрирайте се:.
        /// </summary>
        public static string NotAccount {
            get {
                return ResourceManager.GetString("NotAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да се регестрирате трябва да сте съгласни с правилата на сайта!.
        /// </summary>
        public static string NotAgreeWithGeneralTermsMsg {
            get {
                return ResourceManager.GetString("NotAgreeWithGeneralTermsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Докторска степен.
        /// </summary>
        public static string Ph_D {
            get {
                return ResourceManager.GetString("Ph.D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете имейл адрес за възстановяване на паролата.
        /// </summary>
        public static string PleaseEnterEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете имейл адрес.
        /// </summary>
        public static string PleaseEnterEmailonly {
            get {
                return ResourceManager.GetString("PleaseEnterEmailonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начално образование.
        /// </summary>
        public static string PrimaryEducation {
            get {
                return ResourceManager.GetString("PrimaryEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилна снимка.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактиране на Моят профил.
        /// </summary>
        public static string ProfileRedaction {
            get {
                return ResourceManager.GetString("ProfileRedaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай се.
        /// </summary>
        public static string RegisterYou {
            get {
                return ResourceManager.GetString("RegisterYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на Бизнес профил.
        /// </summary>
        public static string RegistrationToBusinessUserProfile {
            get {
                return ResourceManager.GetString("RegistrationToBusinessUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на Потребителски профил.
        /// </summary>
        public static string RegistrationToUserProfile {
            get {
                return ResourceManager.GetString("RegistrationToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задаване на нова парола.
        /// </summary>
        public static string ResetPass {
            get {
                return ResourceManager.GetString("ResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нулиране на парола.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средно образование.
        /// </summary>
        public static string Secondaryeducat {
            get {
                return ResourceManager.GetString("Secondaryeducat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умения.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to София.
        /// </summary>
        public static string Sofia {
            get {
                return ResourceManager.GetString("Sofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посочете сферата, в която бихте искали да работите.
        /// </summary>
        public static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общите условия.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят не е намерен.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителски профил.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa..
        /// </summary>
        public static string UserProfileDescriptionMsg {
            get {
                return ResourceManager.GetString("UserProfileDescriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варна.
        /// </summary>
        public static string Varna {
            get {
                return ResourceManager.GetString("Varna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искам профилът ми да бъде видим за фирмите..
        /// </summary>
        public static string VisibleProfile {
            get {
                return ResourceManager.GetString("VisibleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професионално училище/колеж.
        /// </summary>
        public static string VocationalSchool_college {
            get {
                return ResourceManager.GetString("VocationalSchool/college", resourceCulture);
            }
        }
    }
}
